In [1]:
import numpy as np

argmax()  : Returns indices of the max element of the array in a particular axis. If axis is not given, then array is flatten into 1D array.

argmin()  : Returns indices of the min element of the array in a particular axis. If axis is not given, then array is flatten into 1D array.


axis=0 means that the operation is performed down the columns of a 2D array.

axis=1 means that the operation is performed down the rows of a 2D array.



1.Axis value is not given  (Note : index starts with 0)


In [2]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])

In [3]:
arr.argmin()

2

axis=0 means that the operation is performed down the columns of a 2D array. (Note : index starts with 0)


In [20]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])
np.argmin(arr,axis=0)

array([1, 1, 0, 0], dtype=int64)

axis=1 means that the operation is performed down the rows of a 2D array. (Note : index starts with 0)


In [22]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])
np.argmin(arr,axis=-1)

array([2, 0, 1], dtype=int64)

In [23]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])
np.argmax(arr,axis=-1)

array([1, 2, 0], dtype=int64)

In [7]:
list= [19,19,5,80]

In [59]:
np.argmax(list,axis=-1)

3

In [17]:
x = np.array([[4,2,3], 
              [1,0,3]])
index_array = np.argmin(x, axis=-1)
# Same as np.min(x, axis=-1, keepdims=True)

In [18]:
index_array

array([1, 1], dtype=int64)

In [16]:
np.min(x, axis=-1, keepdims=False)

array([2, 0])

axis=0 means that the operation is performed down the columns of a 2D array.

axis=1 means that the operation is performed down the rows of a 2D array.


In [24]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])
np.argmax(arr,axis=0)

array([2, 0, 2, 2], dtype=int64)

In [53]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])
np.argmax(arr,axis=1)

array([1, 2, 0], dtype=int64)

In [54]:
arr = np.array([[21,100,3,4],
                [11,12,20,13],
                [56,21,34,45]])
np.argmax(arr,axis=-1)

array([1, 2, 0], dtype=int64)

In [50]:
np.take_along_axis(arr, np.expand_dims(index_array, axis=1), axis=1)

array([[100],
       [ 20],
       [ 56]])

In [68]:
x1= np.array([0,100,12,34,])

In [69]:
np.argmax(x1,axis=-1)

1