In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([4,5,6])

In [4]:
np.add(a,b)

array([5, 7, 9])

In [5]:
np.subtract(a,b)

array([-3, -3, -3])

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([4, 5, 6])

In [8]:
np.multiply(a,b)

array([ 4, 10, 18])

In [9]:
a

array([1, 2, 3])

In [10]:
b

array([4, 5, 6])

In [11]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [12]:
a

array([1, 2, 3])

In [13]:
b

array([4, 5, 6])

In [14]:
np.mod(a,b)

array([1, 2, 3], dtype=int32)

In [15]:
a

array([1, 2, 3])

In [16]:
b

array([4, 5, 6])

In [17]:
np.power(a,b)

array([  1,  32, 729], dtype=int32)

In [18]:
a

array([1, 2, 3])

In [19]:
b

array([4, 5, 6])

In [21]:
a= np.array([[0,1,2],
         [3,4,5],
         [6,7,8]])

In [22]:
np.max(a)

8

In [23]:
np.min(a)

0

In [24]:
np.std(a)

2.581988897471611

In [25]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])