In [1]:
import numpy as np

In [2]:
a=np.arange(11,20)

In [3]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
x =a>15
x

array([False, False, False, False, False,  True,  True,  True,  True])

In [16]:
a[x]

array([16, 17, 18, 19])

In [7]:
a[a%2==0]

array([12, 14, 16, 18])

In [10]:
x= np.where(a>15)

In [11]:
a[x]

array([16, 17, 18, 19])

In [13]:
a[np.where(a%2==0)]

array([12, 14, 16, 18])

How to get the positions where elements of two arrays match?

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a[np.where(a == b)]
#> (array([1, 3, 5, 7]),)

array([2, 2, 4, 4])

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

How to extract all numbers between a given range from a numpy array?

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
index = np.where((a >= 5) & (a <= 10))

In [32]:
a[index]

array([5, 6])

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [28]:
x=(a>=5) & (a<=10)

In [29]:
a[x]

array([5, 6])