In [53]:
import numpy as np

In [ ]:
np.eye()

In [ ]:
np.eye()

In [54]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [55]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [56]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [57]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(3,3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(3,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [61]:
np.eye(3,3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.eye(3,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [63]:
np.eye(3,3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [64]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])