In [1]:
import numpy as np

In [3]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [4]:
np.linspace(2.0, 3.0, num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [5]:
np.linspace(2.0, 3.0, num=5,endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [7]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [8]:
np.random.randint(2, size=10)

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [9]:
x1 = np.random.randint(10,20,15)
x2 = np.random.randint(11,25,15)
x3 = np.random.randint(14,29,15)

In [10]:
arr = np.array([x1,x2,x3])

In [11]:
arr

array([[18, 19, 15, 15, 16, 14, 12, 18, 15, 18, 16, 18, 13, 18, 19],
       [21, 21, 15, 14, 24, 18, 15, 20, 17, 19, 20, 18, 22, 17, 14],
       [20, 16, 22, 20, 22, 18, 21, 18, 28, 24, 28, 18, 23, 19, 17]])