In [3]:
import numpy as np

In [4]:
numpy = np.array([1,3.5,10])

In [5]:
numpy

array([ 1. ,  3.5, 10. ])

In [6]:
list_python = [1,3.5,10]

In [7]:
list_python

[1, 3.5, 10]

In [8]:
numpy = np.array([1,"priyang",10])

In [9]:
numpy

array(['1', 'priyang', '10'], dtype='<U11')

In [10]:
numpy = np.array([1,"hello",3.5])

In [11]:
numpy

array(['1', 'hello', '3.5'], dtype='<U11')

In [12]:
numpy = np.array([1,True,False])

In [13]:
numpy

array([1, 1, 0])

In [14]:
list1 = [10,20,30]
list2= [20,30,40]

In [15]:
list1 + list2

[10, 20, 30, 20, 30, 40]

In [16]:
arr1 = np.array([10,20,30])
arr2 =np.array([20,30,40])

In [17]:
arr1 + arr2

array([30, 50, 70])